version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-and-lint:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: Running tests
          command: yarn tsc

workflows:
  build:
    jobs:
      - test-and-lint
