version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/node:12.20.0
    steps:
      - checkout
      - run:
          name: Install dependenciesgit 
          command: yarn
      - run:
          name: Running typescript
          command: yarn tsc

workflows:
  build:
    jobs:
      - test-and-lint
