version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Running typescript
          command: yarn tsc
      - run:
          name: Running eslint
          command: yarn lint

workflows:
  build:
    jobs:
      - test-and-lint
